---
- hosts: microk8s
  become: true  # Gain root privileges
  remote_user: genaiuser
  gather_facts: no
  tasks:
    - name: Add line in a file
      ansible.builtin.lineinfile:
        path: /etc/sudoers
        line: 'genaiuser ALL=(ALL) NOPASSWD: ALL'

    - name: Update package lists
      apt: update_cache=yes

    - name: Install required packages
      apt:
        name:
          - snapd
          - jq
          - curl



    - name: Install microk8s using snap
      snap:
        name: microk8s
        classic: true

    - name: Add user to "microk8s" group for access to Kubernetes resources
      user:
        name: "genaiuser"  # Replace with your username
        groups: microk8s
        append: yes

    - name: Start microk8s
      command: microk8s start

    - name: create alias to kubectl microk8s
      command: snap alias microk8s.kubectl kubectl
  
    - name: Enable microk8s common modules
      command: microk8s enable dashboard hostpath-storage

    - name: get quick install file
      command: wget "https://raw.githubusercontent.com/kserve/kserve/release-0.11/hack/quick_install.sh"

    - name: Add line in quick install file
      ansible.builtin.lineinfile:
        path: ./quick_install.sh
        insertafter: 'export ISTIO_VERSION=1.17.2'
        line: 'export KUBECONFIG=/var/snap/microk8s/current/credentials/client.config'
    - name: Find out playbook's path
      shell: pwd
      register: playbook_path_output
    - debug: var=playbook_path_output.stdout

    # - name: lets install kserve now
    #   become: true 
    #   command:  sudo bash quick_install.sh
    
    
    
      